### PR TITLE
Add treefy command

### PR DESCRIPTION
**Pull request by garulovilla**
Add command to convert indented line block to an ASCII directory tree.

### CODE REVIEW

**Comment by hluk** [comment]
Very cool.

It looks like the root element name is ignored.

**Comment by garulovilla** [comment]
Do you mean the dialog that asks about the root element? The initial objective was only ask if add a root element with a default value but I think is a good idea make the change to add the root element name that the user insert. Let me changed.

**Comment by garulovilla** [comment]
Done!

**Comment by hluk** [comment]
Nice, thanks!

**Pull request merged**
