### PR TITLE
Fix 'Clear Clipboard Tab' not working when there are pinned items

### PR DESCRIPTION
**Pull request by zyw271828**

### CODE REVIEW

**Comment by hluk** [comment]
Thanks for the PR.

Couple of problems:
- `plugins.itempinned.isPinned()` only works if the "Pinned Items" plugins is available
- it retrieves data (format `application/x-copyq-item-pinned`) for each item separately in a loop which could be slow with many items

It would be probably better to add some better support for filtering items from scripts or adding a new function to remove all rows when possible and skip the pinned rows.

**Comment by hluk** [comment]
> It would be probably better to add some better support for filtering items from scripts or add a new function to remove all rows when possible and skip the pinned rows.

I've created https://github.com/hluk/CopyQ/pull/1746 which would allow among other things:

```js
ItemSelection(tabName).filterRemovable().removeAll();
```

Comments are welcome.

**Comment by zyw271828** [comment]
This will make writing scripts very convenient, thank you!

Actually, I think it would be better to make "Clear all" a built-in feature instead of a script function. The clipboard of Windows 10 provides [this feature](https://www.howtogeek.com/wp-content/uploads/2020/05/click_clear_all.png), and Windows 11 puts it in a [more prominent position](https://preview.redd.it/zd4damltpj871.png?width=589&format=png&auto=webp&s=9d2a10dd95f73743c19a062eadae04f91ab01221). Microsoft may think that the usage rate of this feature is high.

**Comment by hluk** [comment]
In the next release, there will be also a predefined command to Clear Current Tab (it will be possible to add it from the Command dialog).

**Pull request closed without merging**
